on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm ci
        npm install @faker-js/faker

      - name: Run Cypress Tests
        run: npx cypress run
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_TELEPHONENO }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_WRONGUSERNAME: ${{ secrets.CYPRESS_INCORRECTPASSWORD }}
